export const templates = [
  {
    id: 'invoice',
    name: 'templateInvoice',
    data: [
      ['', 'INVOICE', '', '', '', ''],
      ['', '', '', '', '', ''],
      ['', 'Billed To:', '', '', 'Invoice #:', '1001'],
      ['', 'Client Name', '', '', 'Date:', new Date().toISOString().split('T')[0]],
      ['', 'Client Address', '', '', 'Due Date:', ''],
      ['', '', '', '', '', ''],
      ['', 'Item Description', 'Qty', 'Unit Price', 'Total', ''],
      ['', 'Example Item 1', 2, 150.00, '=C8*D8', ''],
      ['', 'Example Item 2', 1, 450.50, '=C9*D9', ''],
      ['', 'Example Item 3', 5, 50.00, '=C10*D10', ''],
      ['', '', '', '', '', ''],
      ['', '', '', 'Subtotal:', '=SUM(E8:E10)', ''],
      ['', '', '', 'Tax (10%):', '=E12*0.1', ''],
      ['', '', '', 'Total:', '=E12+E13', ''],
      ['', '', '', '', '', ''],
      ['', 'Thank you for your business!', '', '', '', ''],
    ],
  },
  {
    id: 'payroll',
    name: 'templatePayroll',
    data: [
        ['Payroll Summary', '', '', '', '', '', ''],
        ['Pay Period:', 'MM/DD/YYYY - MM/DD/YYYY', '', '', '', '', ''],
        [],
        ['Employee Name', 'Pay Rate', 'Hours Worked', 'Gross Pay', 'Taxes (20%)', 'Net Pay', ''],
        ['John Doe', 25.00, 40, '=B5*C5', '=D5*0.2', '=D5-E5', ''],
        ['Jane Smith', 30.00, 38, '=B6*C6', '=D6*0.2', '=D6-E6', ''],
        ['Peter Jones', 22.50, 42, '=B7*C7', '=D7*0.2', '=D7-E7', ''],
        [],
        ['Totals', '', '=SUM(C5:C7)', '=SUM(D5:D7)', '=SUM(E5:E7)', '=SUM(F5:F7)', ''],
    ],
  },
  {
    id: 'expenseReimbursement',
    name: 'templateExpense',
    data: [
        ['Expense Reimbursement Form', '', '', '', ''],
        ['Employee Name:', 'Your Name', '', 'Department:', 'Your Department'],
        ['Report Period:', '', '', '', ''],
        [],
        ['Date', 'Category', 'Description', 'Amount', ''],
        ['2024-01-05', 'Travel', 'Client Meeting Lunch', 55.00, ''],
        ['2024-01-06', 'Office Supplies', 'New Keyboard', 75.99, ''],
        ['2024-01-08', 'Travel', 'Taxi to airport', 40.00, ''],
        [],
        ['', '', 'Total:', '=SUM(D6:D8)', ''],
    ],
  },
  {
    id: 'balanceSheet',
    name: 'templateBalanceSheet',
    data: [
        ['Balance Sheet', '', '', 'As of Date:', new Date().toISOString().split('T')[0]],
        [],
        ['ASSETS', '', '', '', ''],
        ['Current Assets', '', '', '', ''],
        ['', 'Cash and Cash Equivalents', 150000, '', ''],
        ['', 'Accounts Receivable', 75000, '', ''],
        ['', 'Inventory', 50000, '', ''],
        ['', 'Total Current Assets', '=SUM(C5:C7)', '', ''],
        [],
        ['Non-Current Assets', '', '', '', ''],
        ['', 'Property, Plant, and Equipment', 350000, '', ''],
        ['', 'Intangible Assets', 25000, '', ''],
        ['', 'Total Non-Current Assets', '=SUM(C11:C12)', '', ''],
        [],
        ['TOTAL ASSETS', '', '=C8+C13', '', ''],
        [],
        ['LIABILITIES AND EQUITY', '', '', '', ''],
        ['Current Liabilities', '', '', '', ''],
        ['', 'Accounts Payable', 60000, '', ''],
        ['', 'Short-term Debt', 40000, '', ''],
        ['', 'Total Current Liabilities', '=SUM(C19:C20)', '', ''],
        [],
        ['Non-Current Liabilities', '', '', '', ''],
        ['', 'Long-term Debt', 200000, '', ''],
        ['', 'Total Non-Current Liabilities', '=C24', '', ''],
        [],
        ['Total Liabilities', '', '=C21+C25', '', ''],
        [],
        ['Shareholders\' Equity', '', '', '', ''],
        ['', 'Common Stock', 100000, '', ''],
        ['', 'Retained Earnings', 250000, '', ''],
        ['', 'Total Equity', '=SUM(C30:C31)', '', ''],
        [],
        ['TOTAL LIABILITIES AND EQUITY', '', '=C27+C32', '', ''],
    ],
  },
  {
    id: 'incomeStatement',
    name: 'templateIncomeStatement',
    data: [
        ['Income Statement', '', ''],
        ['For the period ending:', new Date().toISOString().split('T')[0], ''],
        [],
        ['Revenue', 1000000, ''],
        ['Cost of Goods Sold (COGS)', 450000, ''],
        ['Gross Profit', '=B4-B5', ''],
        [],
        ['Operating Expenses', '', ''],
        ['  Sales, General & Admin', 250000, ''],
        ['  Research & Development', 100000, ''],
        ['Total Operating Expenses', '=SUM(B9:B10)', ''],
        [],
        ['Operating Income (EBIT)', '=B6-B11', ''],
        ['Interest Expense', 20000, ''],
        ['Income Before Tax', '=B13-B14', ''],
        ['Income Tax Expense (30%)', '=B15*0.3', ''],
        ['Net Income', '=B15-B16', ''],
    ],
  },
  {
    id: 'cashFlow',
    name: 'templateCashFlow',
    data: [
        ['Cash Flow Statement', ''],
        ['For the period ending:', new Date().toISOString().split('T')[0]],
        [],
        ['Cash Flow from Operating Activities', ''],
        ['  Net Income', 250000],
        ['  Depreciation & Amortization', 50000],
        ['  Changes in Working Capital', -20000],
        ['Net Cash from Operating Activities', '=SUM(B5:B7)'],
        [],
        ['Cash Flow from Investing Activities', ''],
        ['  Purchase of Equipment', -150000],
        ['  Sale of Assets', 25000],
        ['Net Cash from Investing Activities', '=SUM(B11:B12)'],
        [],
        ['Cash Flow from Financing Activities', ''],
        ['  Issuance of Stock', 10000],
        ['  Repayment of Debt', -50000],
        ['Net Cash from Financing Activities', '=SUM(B16:B17)'],
        [],
        ['Net Change in Cash', '=B8+B13+B18'],
        ['Beginning Cash Balance', 100000],
        ['Ending Cash Balance', '=B20+B21'],
    ],
  },
  {
    id: 'budget',
    name: 'templateBudget',
    data: [
        ['Monthly Budget', 'Budgeted', 'Actual', 'Difference', ''],
        [],
        ['Income', '', '', '', ''],
        ['  Salary', 5000.00, 5000.00, '=C4-B4', ''],
        ['  Other', 200.00, 150.00, '=C5-B5', ''],
        ['Total Income', '=SUM(B4:B5)', '=SUM(C4:C5)', '=C6-B6', ''],
        [],
        ['Expenses', '', '', '', ''],
        ['  Rent/Mortgage', 1500.00, 1500.00, '=C9-B9', ''],
        ['  Utilities', 200.00, 225.00, '=C10-B10', ''],
        ['  Groceries', 600.00, 550.75, '=C11-B11', ''],
        ['  Transportation', 150.00, 180.25, '=C12-B12', ''],
        ['  Entertainment', 250.00, 300.00, '=C13-B13', ''],
        ['Total Expenses', '=SUM(B9:B13)', '=SUM(C9:C13)', '=C14-B14', ''],
        [],
        ['Net Savings', '=B6-B14', '=C6-C14', '=C16-B16', ''],
    ],
  }
];
