'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Wand2, Loader2 } from 'lucide-react';
import NextImage from 'next/image';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { generateImage } from '@/ai/flows/generate-image-from-text';

const formSchema = z.object({
  prompt: z.string().min(3, 'Prompt must be at least 3 characters.'),
});

interface ImageGenerationDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onImageGenerated: (imageUrl: string, prompt: string) => void;
}

export function ImageGenerationDialog({ open, onOpenChange, onImageGenerated }: ImageGenerationDialogProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const { toast } = useToast();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      prompt: '',
    },
  });

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    setIsLoading(true);
    setGeneratedImage(null);
    try {
      const result = await generateImage({ promptText: values.prompt });
      if (result.imageDataUri) {
        setGeneratedImage(result.imageDataUri);
      } else {
        throw new Error('Image generation failed to return an image.');
      }
    } catch (error) {
      console.error(error);
      toast({
        variant: 'destructive',
        title: 'Oh no! Something went wrong.',
        description: 'Failed to generate image. Please try again.',
      });
    } finally {
      setIsLoading(false);
    }
  };
  
  const handleOpenChange = (isOpen: boolean) => {
    if (!isOpen) {
      form.reset();
      setGeneratedImage(null);
      setIsLoading(false);
    }
    onOpenChange(isOpen);
  };
  
  const handleAddToChat = () => {
    if(generatedImage) {
      onImageGenerated(generatedImage, form.getValues('prompt'));
      handleOpenChange(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle className="flex items-center">
            <Wand2 className="mr-2 h-5 w-5" /> AI Image Generation
          </DialogTitle>
          <DialogDescription>
            Describe the image you want Sasha to create. Be as descriptive as you like!
          </DialogDescription>
        </DialogHeader>
        <div className="py-4">
          {generatedImage && !isLoading ? (
            <div className="relative aspect-square w-full">
              <NextImage
                src={generatedImage}
                alt="Generated by AI"
                fill
                className="rounded-md object-cover"
                data-ai-hint="abstract art"
              />
            </div>
          ) : isLoading ? (
            <div className="flex justify-center items-center h-48 bg-muted rounded-md">
              <div className="flex flex-col items-center space-y-2">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="text-muted-foreground">Generating your masterpiece...</p>
              </div>
            </div>
          ) : (
             <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                <FormField
                  control={form.control}
                  name="prompt"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Prompt</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., A cute cat wearing a wizard hat" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                 <DialogFooter>
                  <Button type="submit" disabled={isLoading}>
                    {isLoading ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Generating...
                      </>
                    ) : (
                      'Generate'
                    )}
                  </Button>
                </DialogFooter>
              </form>
            </Form>
          )}
        </div>
         {generatedImage && !isLoading && (
          <DialogFooter>
            <Button variant="outline" onClick={() => { setGeneratedImage(null); form.reset(); }}>Generate Another</Button>
            <Button onClick={handleAddToChat}>Add to Chat</Button>
          </DialogFooter>
        )}
      </DialogContent>
    </Dialog>
  );
}
