'use client';

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: { [key: string]: string | number }) => string;
  dir: 'ltr' | 'rtl';
}

const translations: { [key in Language]: { [key: string]: string } } = {
  en: {
    pageTitle: 'Sasha Banking',
    initialMessage: "Hello! I'm Sasha, your financial advisor. How can I help you today?",
    placeholder: "Message Sasha...",
    uploadCsvTooltip: "Upload Loan CSV",
    uploadPdfTooltip: "Upload Financial PDF",
    micTooltip: "Use Microphone",
    sendSr: "Send",
    analyzingFile: "Context: {{fileName}}",
    clearPdfTooltip: "Clear PDF from session",
    pdfClearedTitle: "PDF Cleared",
    pdfClearedDesc: "The document has been removed from the session.",
    clearedPdfMessage: "I have cleared the previous document. How can I assist you now?",
    csvUploadTitle: "CSV File Uploaded",
    csvUploadDesc: "{{fileName}} is ready for loan analysis.",
    pdfUploadTitle: "PDF File Uploaded",
    pdfUploadDesc: "{{fileName}} is ready for chat.",
    pdfLoadedForChat: "I've loaded {{fileName}}. Feel free to ask me any questions about it.",
    analyzingPdfMessage: "Analyzing the financial statement: {{fileName}}...",
    analysisFailedTitle: "Analysis Failed",
    analysisFailedDesc: "Sasha could not analyze the financial statement. Please try again.",
    unableToAnalyzeMessage: 'Sorry, I was unable to analyze that document.',
    loanAnalysisHeader: "Here is the analysis for Loan ID **{{loanId}}**:",
    financialAnalysisHeader: "Here is the analysis of the financial statement:",
    uploadCsvFirst: 'Please upload a CSV file first.',
    invalidPdfTitle: 'Invalid File Type',
    invalidPdfDesc: 'Please upload a PDF file.',
    sessionSaveErrorTitle: 'Could not save session',
    sessionSaveErrorDesc: 'Your browser may be out of space or in private mode.',
    documentLoadedTitle: 'Document Loaded',
    documentLoadedDesc: "Continuing session with {{fileName}}.",
    genericErrorTitle: 'Oh no! Something went wrong.',
    genericErrorDesc: 'Failed to get a response from Sasha. Please try again.',
    loanAnalysisReportTitle: "Loan Analysis Report",
    financialAnalysisReportTitle: "Financial Statement Analysis",
    summary: "Summary",
    prediction: "Prediction",
    eligibility: "Eligibility",
    creditScoreAssessment: "Credit Score Assessment",
    downloadPdf: "Download PDF",
    english: 'English',
    arabic: 'Arabic',
    choosePdfLanguageTitle: "Choose PDF Language",
    choosePdfLanguageDesc: "In which language would you like to download the report?",
    cancel: "Cancel",
    clearCsvTooltip: "Clear CSV from session",
    csvClearedTitle: "CSV Cleared",
    csvClearedDesc: "The CSV data has been cleared from the session.",
    clearedCsvMessage: "I have cleared the CSV data. How can I help you now?",
    translationErrorTitle: 'Translation Error',
    translationErrorDesc: 'Failed to generate the report in {{lang}}. Please try again.',
    generatingTranslatedPdf: 'Generating translated PDF...',
    trendsAndGraphsTitle: "Trends & Visualizations",
    identifiedFlawsTitle: "Identified Flaws & Risks",
    financialPerformanceTitle: "Financial Performance",
    revenue: "Revenue",
    netIncome: "Net Income",
    pdfGenerationError: "Could not generate the PDF report.",
    maintenanceMessage: "Services are undergoing maintenance and major upgrades. Time remaining: {{time}}",
    imageDialogTitle: "AI Image Generation",
    imageDialogDesc: "Describe the image you want Sasha to create. Be as descriptive as you like.",
    promptLabel: "Prompt",
    promptPlaceholder: "e.g., A futuristic city skyline at sunset",
    generateButton: "Generate",
    generatingMessage: "Sasha is creating your image...",
    generateAnotherButton: "Generate Another",
    downloadButton: "Download",
    addToChatButton: "Add to Chat",
    imageGenSuccess: "Here is the image I created based on your prompt: \"{{prompt}}\"",
    imageGenFailedTitle: "Image Generation Failed",
    imageGenFailedDesc: "Sorry, I couldn't create an image at this time. Please try again later.",
    imageGenDisclaimer: "Sasha's creative abilities are powered by a specialized image generation model. Generated images are for creative use.",
    newSessionButton: "New Session",
    newSessionTitle: "New Session Started",
    newSessionDesc: "Your chat has been cleared.",
    newSessionDescSpreadsheet: "Your spreadsheet and chat have been cleared.",
    newSessionDescDA: "Your data analysis dashboard has been cleared.",
    newSessionConfirmTitle: "Are you sure?",
    newSessionConfirmDescChat: "This will clear your entire chat history and remove any uploaded files. This action cannot be undone.",
    newSessionConfirmDescSpreadsheet: "This will clear your entire spreadsheet, including data and charts, and reset the chat. This action cannot be undone.",
    newSessionConfirmButton: "Start New Session",

    // Sasha Status
    sashaStatusOffline: 'Offline',
    sashaOfflineTitle: 'Sasha is Offline',
    sashaOfflineDesc: 'Sasha is currently recharging. She will be back online during working hours.',
    sashaOnlineAgain: 'Online again in:',
    sashaOfflineHours: 'Working Hours: 5:30 AM - 5:30 PM & 5:45 PM - 6:30 PM',

    // Nav
    chatTitle: 'Chat',
    aboutTitle: 'About Sasha',
    spreadsheetTitle: 'Spreadsheet',
    spreadsheetGuideTitle: 'Spreadsheet Guide',
    dataAnalyticsTitle: 'Data Analytics',
    knowledgeBaseTitle: 'Knowledge Base',

    // Knowledge Base Page
    kbHeader: "Sasha's Knowledge Base",
    kbSubHeader: "Add your own custom instructions, rules, or data that Sasha will remember across all conversations. This is your personal extension to Sasha's brain.",
    kbPlaceholder: "Enter your custom notes here...\n\nFor example:\n- Never suggest investing in cryptocurrency.\n- When I ask for a market summary, always include the VIX index.\n- My company's fiscal year ends in June.",
    kbSaveButton: 'Save Knowledge',
    kbSavingButton: 'Saving...',
    kbSaveSuccessTitle: 'Knowledge Base Saved',
    kbSaveSuccessDesc: "Sasha's knowledge has been updated.",
    kbSaveErrorTitle: 'Save Failed',
    kbSaveErrorDesc: 'Could not save your notes. Please try again.',
    kbLoadErrorTitle: 'Load Failed',
    kbLoadErrorDesc: 'Could not load your knowledge base notes.',


    // Learn Page -> About Page
    learnPageTitle: 'About Sasha',
    learnIntro: 'Sasha is an advanced, AI-powered financial strategist and banking assistant designed to bring institutional-grade analysis and agentic task execution to your fingertips. Interact naturally, get deep insights, and automate complex tasks with ease.',
    learnCapabilitiesTitle: "Sasha's Core Capabilities",
    learnChatTitle: 'Institutional-Grade Financial Intelligence',
    learnChatDesc: "Engage with an AI that understands the nuances of finance. Upload complex financial statements, credit reports from bureaus like Oman's Mala'a, or internal loan data. Sasha doesn't just read; she comprehends, synthesizes, and critiques. Ask her to 'Identify key risks in this balance sheet,' 'Benchmark this company's P/E ratio against industry standards,' or 'Draft a summary for the credit committee.' Sasha provides instant, institutional-quality analysis in both English and Arabic, becoming an indispensable partner for credit officers, analysts, and decision-makers.",
    learnSpreadsheetTitle: 'The Truly Agentic Spreadsheet',
    learnSpreadsheetDesc: "This is not just a spreadsheet; it's an intelligent workspace. Command Sasha with natural language to perform tasks that once took hours. Say 'Create a 5-year financial forecast based on this historical data,' 'Generate a Gantt chart for the Q4 product launch,' or 'Analyze these sales figures and highlight all regions that underperformed by 15%.' Sasha functions as a state-of-the-art AI architect, understanding your intent, structuring the data, applying formats, and executing complex operations instantly, transforming your productivity.",
    learnDATitle: 'Sasha Data Analytics: Your BI Co-Pilot',
    learnDADesc: "Transform raw data into actionable insights with a fully conversational BI engine. Upload CSV, Excel, or PDF files, and Sasha will instantly generate an interactive dashboard with key metrics, charts, and tables. Continue the conversation to request new visualizations on the fly. Ask Sasha to 'Show me total sales by region as a bar chart,' or 'create a pie chart for customer segments.' Sasha acts as your personal data engineer and BI developer, turning complex data into clear, interactive visuals.",
    learnAITitle: 'Powered by a State-of-the-Art AI Architecture',
    learnAIDesc: "Sasha is built on a private, state-of-the-art AI architecture. This enables her to understand complex documents, reason about data, follow multi-step instructions, and generate human-like text, making her a powerful and versatile financial partner.",
    learnSecurityTitle: 'Enterprise-Grade Security & Privacy',
    learnSecurityDesc: "Sasha is engineered with security as a foundational principle. Operating within a private, state-of-the-art architecture, all data processing and interactions are handled with the strictest confidentiality. Your financial statements, proprietary data, and sensitive conversations are never used for external training models. With end-to-end encryption and robust access controls, Sasha provides a secure, compliant environment that meets the rigorous standards of financial institutions, ensuring your most critical information remains protected.",
    learnWhoBenefitsTitle: 'Who Benefits from Sasha?',
    learnRoleAnalystTitle: 'The Financial Analyst',
    learnRoleAnalystDesc: 'Accelerate your research, data modeling, and report generation. Let Sasha handle the repetitive tasks so you can focus on strategic insights.',
    learnRoleOfficerTitle: 'The Credit Officer',
    learnRoleOfficerDesc: 'Gain a deeper, faster understanding of applicant risk. Analyze financial statements and credit reports in seconds to make more informed decisions.',
    learnRoleExecutiveTitle: 'The Executive',
    learnRoleExecutiveDesc: 'Access high-level summaries and key metrics on demand. Stay informed and drive strategy without getting bogged down in the details.',
    gettingStartedTitle: "Getting Started: A Quick Guide",
    gsChatStepTitle: "1. Start a Conversation",
    gsChatStepDesc: "Navigate to the <strong>Chat</strong> page. You can start talking to Sasha immediately. For more powerful analysis, use the upload buttons in the message bar to provide a PDF or CSV file as context for your conversation.",
    gsSpreadsheetStepTitle: "2. Command Your Spreadsheet",
    gsSpreadsheetDesc: "Go to the <strong>Spreadsheet</strong> page. Use the integrated chat sidebar to give Sasha commands. You can also import your own Excel files using the toolbar to have Sasha work with your own data.",
    gsDAStepTitle: "3. Analyze Your Data",
    gsDAStepDesc: "Head to the <strong>Data Analytics</strong> page. Upload your dataset (Excel, CSV, PDF), and Sasha will instantly build a dashboard. Use the chat to ask for more specific insights and visualizations.",
    
    comingSoonSashaTitle: "The Future of Sasha: AI Capabilities",
    comingSoonSashaDesc: "Sasha's evolution is relentless. Our roadmap is focused on building the most powerful, proactive AI financial agent.",
    csSashaFeature1: "Proactive Insights & Anomaly Detection",
    csSashaFeature2: "Real-time Market Data Integration (stocks, forex)",
    csSashaFeature3: "Personalized Financial Health Dashboards",
    csSashaFeature4: "Advanced Voice & Speech Interaction",
    csSashaFeature5: "Secure Document Vault & Management",
    csSashaFeature6: "Automated Report Generation & Scheduling",
    csSashaFeature7: "Predictive Cash Flow Forecasting",
    csSashaFeature8: "Calendar & Email Integration for Financial Reminders",
    csSashaFeature9: "Multi-document Cross-Referencing & Analysis",
    csSashaFeature10: "Goal-based Savings & Investment Planning",
    csSashaFeature11: "Secure API for Enterprise Integration",
    csSashaFeature12: "Natural Language Querying of Databases",
    csSashaFeature13: "Compliance & Regulatory Change Monitoring",
    csSashaFeature14: "Customer Sentiment Analysis from Communications",
    csSashaFeature15: "Custom Agentic Workflow Automation",

    comingSoonSpreadsheetTitle: "The Future of Spreadsheets: Agentic Power",
    comingSoonSpreadsheetDesc: "The spreadsheet is becoming a fully autonomous workspace, powered by Sasha.",
    csSpreadsheetFeature1: "Natural Language Formula Generation",
    csSpreadsheetFeature2: "Automatic Chart & Graph Creation from Data",
    csSpreadsheetFeature3: "AI-Powered Data Validation Rules",
    csSpreadsheetFeature4: "Instant Pivot Table Creation via Chat",
    csSpreadsheetFeature5: "Automated Data Cleaning & Deduplication",
    csSpreadsheetFeature6: "Intelligent Conditional Formatting",
    csSpreadsheetFeature7: "Real-time Stock & Financial Data in Cells",
    csSpreadsheetFeature8: "Automated Data Import from Web Sources",
    csSpreadsheetFeature9: "Live Collaborative Editing with AI Assistance",
    csSpreadsheetFeature10: "Full Version History with AI Summaries",
    
    comingSoonDATitle: "The Future of Analytics: An Agentic BI Engine",
    comingSoonDADesc: "We are evolving Sasha into a fully-fledged, AI-native Business Intelligence platform that rivals traditional tools.",
    csDAFeature1: "Interactive Dashboard Generation from Chat",
    csDAFeature2: "Power Query-like Visual Data Transformation Tools",
    csDAFeature3: "Natural Language to DAX-style Expressions",
    csDAFeature4: "Automated Data Storytelling and Report Building",
    csDAFeature5: "Real-time Anomaly Detection and Alerts",
    csDAFeature6: "Predictive Analytics and Forecasting Models",
    csDAFeature7: "Multi-Source Data Joins and Blending",
    csDAFeature8: "AI-powered Root Cause Analysis",
    csDAFeature9: "Custom Visuals and API Extensibility",
    csDAFeature10: "Automated ETL Pipeline Creation",

    getStartedSasha: 'GET STARTED WITH SASHA',
    getStartedSpreadsheet: 'Or, get started with the Spreadsheet',

    // Spreadsheet Page
    chatWithSasha: "Chat with Sasha",
    closeChat: "Close chat",
    sashaSpreadsheetHello: "Hello! I am a fully-featured agentic spreadsheet assistant. I can help you with data entry, financial modeling, charts, and more. How can I help you?",
    spreadsheetPlaceholder: "e.g., Create an invoice template",
    send: "Send",
    showChat: "Show Chat",
    hideChat: "Hide Chat",
    importSuccessTitle: "Import Successful",
    importSuccessDesc: "Successfully imported \"{{fileName}}\".",
    importFailedTitle: "Import Failed",
    importFailedDesc: "There was an error processing your Excel file.",
    sashaSpreadsheetFileLoaded: "I've loaded \"{{fileName}}\" into the spreadsheet. How can I help you with it?",
    sashaSpreadsheetError: "Sorry, I ran into an issue. Please try that again.",
    toolbarFile: "File",
    toolbarTemplates: "Templates",
    templateInvoice: "Invoice",
    templatePayroll: "Payroll",
    templateExpense: "Expense Reimbursement",
    templateBalanceSheet: "Balance Sheet",
    templateIncomeStatement: "Income Statement",
    templateCashFlow: "Cash Flow Statement",
    templateBudget: "Monthly Budget",
    templateGantt: "Project Gantt Chart",
    templateGeneralLedger: "General Ledger",
    templateSalesLedger: "Sales Ledger",
    templatePurchaseLedger: "Purchase Ledger",
    templateFinancialModel: '3-Statement Financial Model',
    templateDCF: 'DCF Valuation',
    templateAppliedTitle: "Template Applied",
    templateAppliedDesc: "The template has been loaded into the sheet.",
    toolbarHome: "Home",
    toolbarInsert: "Insert (Soon)",
    toolbarFormulas: "Formulas (Soon)",
    toolbarData: "Data (Soon)",
    toolbarReview: "Review (Soon)",
    toolbarView: "View (Soon)",
    toolbarFullscreen: "Fullscreen",
    toolbarExitFullscreen: "Exit Fullscreen",
    toolbarDownload: "Download",
    toolbarImport: "Import",
    tooltipPaste: "Paste (Ctrl/Cmd+V)",
    tooltipCut: "Cut",
    tooltipCopy: "Copy",
    tooltipFormatPainter: "Format Painter (Soon)",
    tooltipBold: "Bold",
    tooltipItalic: "Italic",
    tooltipUnderline: "Underline",
    tooltipFontColor: "Font Color",
    tooltipFillColor: "Fill Color",
    tooltipAlignLeft: "Align Left",
    tooltipCenter: "Center",
    tooltipAlignRight: "Align Right",
    tooltipWrapText: "Wrap Text",
    tooltipMergeCenter: "Merge & Center",
    tooltipAutoSum: "AutoSum (Soon)",
    tooltipSortFilter: "Sort & Filter (Soon)",
    tooltipFindSelect: "Find & Select (Soon)",
    chartsTitle: "Charts",
    
    // Spreadsheet Guide Page
    sgTitle: "Spreadsheet Guide",
    sgHeader: "The Agentic Spreadsheet",
    sgSubHeader: "This isn't just a grid of cells. It's an intelligent workspace where you command the AI to perform complex tasks. This guide will show you how.",
    sgCoreCapabilitiesTitle: "Core Capabilities",
    sgFeatureAIAssistantTitle: "AI Assistant",
    sgFeatureAIAssistantDesc: "Use natural language in the chat panel to command Sasha to perform any task, from data entry to complex financial modeling.",
    sgFeatureTemplatesTitle: "Powerful Templates",
    sgFeatureTemplatesDesc: "Jumpstart your work with a library of professional, pre-built templates for accounting, finance, and project management.",
    sgFeatureFormulasTitle: "Full-Featured Formulas",
    sgFeatureFormulasDesc: "Leverage a massive library of hundreds of functions, just like in a traditional spreadsheet application. Sasha can build formulas for you.",
    sgFeatureDataToolsTitle: "Advanced Data Tools",
    sgFeatureDataToolsDesc: "Ask Sasha to sort, filter, find duplicates, or even create pivot-table-like summaries on the fly.",
    sgGettingStartedTitle: "How It Works: Your 3-Step Workflow",
    sgGettingStartedDesc: "Working with the Agentic Spreadsheet is a simple, conversational process.",
    sgStep1Title: "Start with Data",
    sgStep1Desc: "You can start with a blank sheet, import an existing Excel/CSV file, or select a pre-built template from the 'Templates' menu.",
    sgStep2Title: "Give Sasha a Command",
    sgStep2Desc: "Use the chat panel on the right to tell Sasha what you want to do in plain English or Arabic.",
    sgStep2Example: "Calculate the net profit for Q3 and highlight it in green.",
    sgStep3Title: "Review the Result",
    sgStep3Desc: "Sasha will interpret your command, perform the necessary operations (like inserting formulas and applying formatting), and confirm the action. The sheet updates instantly.",
    sgStep3Example: "Done. I've calculated the net profit in cell E14 and applied the formatting.",
    sgSashaCommandsTitle: "Example Commands for Sasha",
    sgCmdDataEntryTitle: "Data Entry & Bookkeeping",
    sgCmdDataEntryDesc: "Sasha can act as your automated bookkeeper.",
    sgCmdDataEntryExample: "Record a sale of 500 units at $12.50 each to 'Example Corp' on today's date.",
    sgCmdFinancialAnalysisTitle: "Financial Analysis & Modeling",
    sgCmdFinancialAnalysisDesc: "Ask Sasha to perform complex financial calculations.",
    sgCmdFinancialAnalysisExample: "What is the Net Present Value of cash flows in C5:C10 with a discount rate of 8%?",
    sgCmdFormattingTitle: "Formatting & Auditing",
    sgCmdFormattingDesc: "Automate visual organization and data validation.",
    sgCmdFormattingExample: "Find all rows where column D is greater than column C and make their background light red.",
    sgCmdChartsTitle: "Charts & Visualization",
    sgCmdChartsDesc: "Turn your data into insights.",
    sgCmdChartsExample: "Create a bar chart showing the total sales by region from columns A and F.",
    sgFunctionLibraryTitle: "Function & Formula Library",
    sgFunctionLibraryDesc: "Sasha is proficient with a vast library of functions and can generate formulas on command. Here are some of the key functions available:",
    sgFuncMathLogicTitle: "Math & Logic",
    sgFuncLookupTitle: "Lookup & Reference",
    sgFuncFinancialTitle: "Financial",
    sgFuncTextTitle: "Text",
    sgFuncDateTimeTitle: "Date & Time",
    sgFuncStatisticalTitle: "Statistical & Forecasting",

    // Data Analytics Page
    daUploadPromptTitle: "AI-Powered Data Dashboard",
    daUploadPromptDesc: "Upload your data file (XLSX, CSV, or PDF) to have Sasha analyze it and generate an interactive dashboard.",
    daUploadButton: "Upload Data File",
    daGeneratingDashboardTitle: "جاري إنشاء لوحة معلومات الذكاء الاصطناعي...",
    daGeneratingDashboardDesc: "يرجى الانتظار بينما تقوم ساشا بتحليل بياناتك وبناء لوحة معلوماتك.",
    analysisResultTitle: "نتيجة التحليل",
    daSummaryTitle: "ملخص الذكاء الاصطناعي",
    daUnsupportedFileType: 'نوع ملف غير مدعوم. يرجى تحميل ملف CSV أو XLSX أو PDF.',
    daAnalysisFailedDesc: 'فشل التحليل. قد يكون الملف تالفًا أو بتنسيق غير مدعوم أو أن نموذج الذكاء الاصطناعي غير متاح حاليًا.',
    daKeyInsightsTitle: 'رؤى رئيسية',
    daDownloadPdfButton: 'تحميل PDF',
    daGeneratingPdfTitle: 'جاري إنشاء تقرير PDF...',
    daPdfGenerationFailedTitle: 'فشل إنشاء PDF',
    daPdfGenerationFailedDesc: 'حدث خطأ أثناء محاولة إنشاء تقرير PDF.',
  },
  ar: {
    pageTitle: 'ساشا المصرفية',
    initialMessage: "مرحباً! أنا ساشا، مستشاركتك المالية. كيف يمكنني مساعدتك اليوم؟",
    placeholder: "راسل ساشا...",
    uploadCsvTooltip: "تحميل ملف CSV للقروض",
    uploadPdfTooltip: "تحميل ملف PDF مالي",
    micTooltip: "استخدام الميكروفون",
    sendSr: "إرسال",
    analyzingFile: "السياق: {{fileName}}",
    clearPdfTooltip: "مسح ملف PDF من الجلسة",
    pdfClearedTitle: "تم مسح PDF",
    pdfClearedDesc: "تمت إزالة المستند من الجلسة.",
    clearedPdfMessage: "لقد قمت بمسح المستند السابق. كيف يمكنني مساعدتك الآن؟",
    csvUploadTitle: "تم تحميل ملف CSV",
    csvUploadDesc: "{{fileName}} جاهز لتحليل القرض.",
    pdfUploadTitle: "تم تحميل ملف PDF",
    pdfUploadDesc: "{{fileName}} جاهز للمحادثة.",
    pdfLoadedForChat: "لقد قمت بتحميل {{fileName}}. لا تتردد في طرح أي أسئلة حوله.",
    analyzingPdfMessage: "جاري تحليل البيان المالي: {{fileName}}...",
    analysisFailedTitle: "فشل التحليل",
    analysisFailedDesc: "لم تتمكن ساشا من تحليل البيان المالي. يرجى المحاولة مرة أخرى.",
    unableToAnalyzeMessage: 'عذراً، لم أتمكن من تحليل ذلك المستند.',
    loanAnalysisHeader: "إليك تحليل معرف القرض **{{loanId}}**:",
    financialAnalysisHeader: "إليك تحليل البيان المالي:",
    uploadCsvFirst: 'يرجى تحميل ملف CSV أولاً.',
    invalidPdfTitle: 'نوع ملف غير صالح',
    invalidPdfDesc: 'يرجى تحميل ملف PDF.',
    sessionSaveErrorTitle: 'تعذر حفظ الجلسة',
    sessionSaveErrorDesc: 'قد تكون مساحة متصفحك ممتلئة أو في وضع التصفح الخاص.',
    documentLoadedTitle: 'تم تحميل المستند',
    documentLoadedDesc: "متابعة الجلسة مع {{fileName}}.",
    genericErrorTitle: 'عفوًا! حدث خطأ ما.',
    genericErrorDesc: 'فشل الحصول على رد من ساشا. يرجى المحاولة مرة أخرى.',
    loanAnalysisReportTitle: "تقرير تحليل القرض",
    financialAnalysisReportTitle: "تحليل البيان المالي",
    summary: "ملخص",
    prediction: "توقع",
    eligibility: "الأهلية",
    creditScoreAssessment: "تقييم الجدارة الائتمانية",
    downloadPdf: "تحميل PDF",
    english: 'الإنجليزية',
    arabic: 'العربية',
    choosePdfLanguageTitle: "اختر لغة التقرير",
    choosePdfLanguageDesc: "بأي لغة تود تحميل التقرير؟",
    cancel: "إلغاء",
    clearCsvTooltip: "مسح ملف CSV من الجلسة",
    csvClearedTitle: "تم مسح CSV",
    csvClearedDesc: "تمت إزالة بيانات CSV من الجلسة.",
    clearedCsvMessage: "لقد قمت بمسح بيانات CSV. كيف يمكنني مساعدتك الآن؟",
    translationErrorTitle: 'خطأ في الترجمة',
    translationErrorDesc: 'فشل إنشاء التقرير باللغة {{lang}}. يرجى المحاولة مرة أخرى.',
    generatingTranslatedPdf: 'جاري إنشاء ملف PDF مترجم...',
    trendsAndGraphsTitle: "الاتجاهات والتصورات",
    identifiedFlawsTitle: "العيوب والمخاطر المحددة",
    financialPerformanceTitle: "الأداء المالي",
    revenue: "الإيرادات",
    netIncome: "صافي الدخل",
    pdfGenerationError: "تعذر إنشاء تقرير PDF.",
    maintenanceMessage: "تخضع الخدمات للصيانة والتحديثات الرئيسية. الوقت المتبقي: {{time}}",
    imageDialogTitle: "إنشاء صورة بالذكاء الاصطناعي",
    imageDialogDesc: "صف الصورة التي تريد أن تنشئها ساشا. كن وصفيًا كما تريد.",
    promptLabel: "الموجه",
    promptPlaceholder: "مثال: أفق مدينة مستقبلية عند غروب الشمس",
    generateButton: "إنشاء",
    generatingMessage: "ساشا تنشئ صورتك...",
    generateAnotherButton: "إنشاء واحدة أخرى",
    downloadButton: "تنزيل",
    addToChatButton: "إضافة إلى الدردشة",
    imageGenSuccess: "هذه هي الصورة التي أنشأتها بناءً على موجهك: \"{{prompt}}\"",
    imageGenFailedTitle: "فشل إنشاء الصورة",
    imageGenFailedDesc: "عذرًا، لم أتمكن من إنشاء صورة في هذا الوقت. يرجى المحاولة مرة أخرى لاحقًا.",
    imageGenDisclaimer: "قدرات ساشا الإبداعية مدعومة بنموذج متخصص لتوليد الصور. الصور المنشأة للاستخدام الإبداعي.",
    newSessionButton: "جلسة جديدة",
    newSessionTitle: "بدأت جلسة جديدة",
    newSessionDesc: "تم مسح محادثتك.",
    newSessionDescSpreadsheet: "تم مسح جدول البيانات والدردشة.",
    newSessionDescDA: "تم مسح لوحة معلومات تحليل البيانات الخاصة بك.",
    newSessionConfirmTitle: "هل أنت متأكد؟",
    newSessionConfirmDescChat: "سيؤدي هذا إلى مسح سجل الدردشة بالكامل وإزالة أي ملفات تم تحميلها. لا يمكن التراجع عن هذا الإجراء.",
    newSessionConfirmDescSpreadsheet: "سيؤدي هذا إلى مسح جدول البيانات بالكامل، بما في ذلك البيانات والمخططات، وإعادة تعيين الدردشة. لا يمكن التراجع عن هذا الإجراء.",
    newSessionConfirmButton: "بدء جلسة جديدة",

    // Sasha Status
    sashaStatusOffline: 'غير متصلة',
    sashaOfflineTitle: 'ساشا غير متصلة',
    sashaOfflineDesc: 'ساشا تقوم بإعادة الشحن حاليًا. ستعود للعمل خلال ساعات الدوام.',
    sashaOnlineAgain: 'متصلة مرة أخرى في:',
    sashaOfflineHours: 'ساعات العمل: 5:30 صباحًا - 5:30 مساءً  و  5:45 مساءً - 6:30 مساءً',
    
    // Nav
    chatTitle: 'الدردشة',
    aboutTitle: 'حول ساشا',
    spreadsheetTitle: 'جدول البيانات',
    spreadsheetGuideTitle: 'دليل جدول البيانات',
    dataAnalyticsTitle: 'تحليل البيانات',
    knowledgeBaseTitle: 'قاعدة المعرفة',
    
    // Knowledge Base Page
    kbHeader: "قاعدة معرفة ساشا",
    kbSubHeader: "أضف تعليماتك وقواعدك وبياناتك المخصصة التي ستتذكرها ساشا في جميع المحادثات. هذا هو امتدادك الشخصي لدماغ ساشا.",
    kbPlaceholder: "أدخل ملاحظاتك المخصصة هنا...\n\nعلى سبيل المثال:\n- لا تقترح أبدًا الاستثمار في العملات المشفرة.\n- عندما أطلب ملخصًا للسوق، قم دائمًا بتضمين مؤشر VIX.\n- تنتهي السنة المالية لشركتي في يونيو.",
    kbSaveButton: 'حفظ المعرفة',
    kbSavingButton: 'جاري الحفظ...',
    kbSaveSuccessTitle: 'تم حفظ قاعدة المعرفة',
    kbSaveSuccessDesc: "تم تحديث معرفة ساشا.",
    kbSaveErrorTitle: 'فشل الحفظ',
    kbSaveErrorDesc: 'تعذر حفظ ملاحظاتك. يرجى المحاولة مرة أخرى.',
    kbLoadErrorTitle: 'فشل التحميل',
    kbLoadErrorDesc: 'تعذر تحميل ملاحظات قاعدة المعرفة الخاصة بك.',

    // Learn Page -> About Page
    learnPageTitle: 'حول ساشا',
    learnIntro: 'ساشا هي خبيرة استراتيجية مالية ومساعدة مصرفية متقدمة تعمل بالذكاء الاصطناعي، مصممة لتوفر لك تحليلات على مستوى المؤسسات وتنفيذ مهام وكيلية بكل سهولة. تفاعل بشكل طبيعي، واحصل على رؤى عميقة، وقم بأتمتة المهام المعقدة.',
    learnCapabilitiesTitle: "قدرات ساشا الأساسية",
    learnChatTitle: 'ذكاء مالي من الطراز المؤسسي',
    learnChatDesc: "تفاعل مع ذكاء اصطناعي يفهم دقائق الأمور المالية. قم بتحميل بيانات مالية معقدة، تقارير ائتمانية من مكاتب مثل 'ملاءة' في عُمان، أو بيانات قروض داخلية. ساشا لا تقرأ فقط؛ بل تفهم، وتحلل، وتنتقد. اطلب منها 'تحديد المخاطر الرئيسية في هذه الميزانية العمومية'، 'مقارنة نسبة السعر إلى الأرباح لهذه الشركة بمعايير الصناعة'، أو 'صياغة ملخص للجنة الائتمان'. تقدم ساشا تحليلاً فوريًا بجودة مؤسسية باللغتين الإنجليزية والعربية، لتصبح شريكًا لا غنى عنه لمسؤولي الائتمان والمحللين وصناع القرار.",
    learnSpreadsheetTitle: 'جدول البيانات الوكيلي الحقيقي',
    learnSpreadsheetDesc: "هذا ليس مجرد جدول بيانات؛ إنها مساحة عمل ذكية. أصدر أوامر لساشا بلغة طبيعية لأداء مهام كانت تستغرق ساعات. قل 'أنشئ توقعات مالية لمدة 5 سنوات بناءً على هذه البيانات التاريخية'، 'أنشئ مخطط جانت لإطلاق منتج الربع الرابع'، أو 'حلل أرقام المبيعات هذه وقم بتمييز جميع المناطق التي كان أداؤها أقل بنسبة 15%'. تعمل ساشا كمهندس معماري للذكاء الاصطناعي على أحدث طراز، حيث تفهم نيتك، وتنظم البيانات، وتطبق التنسيقات، وتنفذ العمليات المعقدة على الفور، مما يغير إنتاجيتك.",
    learnDATitle: 'تحليلات بيانات ساشا: مساعدك في ذكاء الأعمال',
    learnDADesc: "حوّل البيانات الأولية إلى رؤى قابلة للتنفيذ باستخدام محرك ذكاء أعمال محادثة بالكامل. قم بتحميل ملفات CSV أو Excel أو PDF، وستقوم ساشا على الفور بإنشاء لوحة معلومات تفاعلية بالمقاييس والرسوم البيانية والجداول الرئيسية. واصل المحادثة لطلب تصورات جديدة أثناء التنقل. اطلب من ساشا 'عرض إجمالي المبيعات حسب المنطقة في مخطط شريطي'، أو 'إنشاء مخطط دائري لشرائح العملاء'. تعمل ساشا كمهندس بيانات ومطور ذكاء أعمال شخصي لك، محولة البيانات المعقدة إلى مرئيات واضحة وتفاعلية.",
    learnAITitle: 'مدعومة ببنية تحتية حديثة للذكاء الاصطناعي',
    learnAIDesc: "ساشا مبنية على بنية تحتية خاصة وحديثة للذكاء الاصطناعي. وهذا يمكنها من فهم المستندات المعقدة، والاستدلال على البيانات، واتباع التعليمات متعددة الخطوات، وإنشاء نصوص شبيهة بالإنسان، مما يجعلها شريكًا ماليًا قويًا ومتعدد الاستخدامات.",
    learnSecurityTitle: 'أمان وخصوصية على مستوى المؤسسات',
    learnSecurityDesc: "تم تصميم ساشا مع اعتبار الأمان مبدأً أساسيًا. تعمل ضمن بنية خاصة وحديثة، حيث يتم التعامل مع جميع عمليات معالجة البيانات والتفاعلات بأقصى درجات السرية. لا يتم استخدام بياناتك المالية، وبيانات الملكية، والمحادثات الحساسة أبدًا لتدريب النماذج الخارجية. مع التشفير من طرف إلى طرف وضوابط الوصول القوية، توفر ساشا بيئة آمنة ومتوافقة تلبي المعايير الصارمة للمؤسسات المالية، مما يضمن حماية معلوماتك الأكثر أهمية.",
    learnWhoBenefitsTitle: 'من يستفيد من ساشا؟',
    learnRoleAnalystTitle: 'المحلل المالي',
    learnRoleAnalystDesc: 'سرّع أبحاثك، ونمذجة البيانات، وإعداد التقارير. دع ساشا تتولى المهام المتكررة حتى تتمكن من التركيز على الرؤى الاستراتيجية.',
    learnRoleOfficerTitle: 'مسؤول الائتمان',
    learnRoleOfficerDesc: 'احصل على فهم أعمق وأسرع لمخاطر المتقدمين. حلل البيانات المالية وتقارير الائتمان في ثوانٍ لاتخاذ قرارات أكثر استنارة.',
    learnRoleExecutiveTitle: 'المدير التنفيذي',
    learnRoleExecutiveDesc: 'احصل على ملخصات عالية المستوى ومقاييس رئيسية عند الطلب. ابق على اطلاع وادفع بالاستراتيجية دون الغرق في التفاصيل.',
    gettingStartedTitle: "البدء: دليل سريع",
    gsChatStepTitle: "١. ابدأ محادثة",
    gsChatStepDesc: "انتقل إلى صفحة <strong>الدردشة</strong>. يمكنك البدء في التحدث إلى ساشا على الفور. لتحليل أقوى، استخدم أزرار التحميل في شريط الرسائل لتوفير ملف PDF أو CSV كسياق لمحادثتك.",
    gsSpreadsheetStepTitle: "٢. تحكم في جدول بياناتك",
    gsSpreadsheetDesc: "اذهب إلى صفحة <strong>جدول البيانات</strong>. استخدم الشريط الجانبي للدردشة المدمج لإعطاء أوامر لساشا. يمكنك أيضًا استيراد ملفات Excel الخاصة بك باستخدام شريط الأدوات لجعل ساشا تعمل مع بياناتك الخاصة.",
    gsDAStepTitle: "٣. حلل بياناتك",
    gsDAStepDesc: "توجه إلى صفحة <strong>تحليل البيانات</strong>. قم بتحميل مجموعة البيانات الخاصة بك (Excel، CSV ،PDF)، وستقوم ساشا على الفور ببناء لوحة معلومات. استخدم الدردشة لطلب المزيد من الأفكار والتصورات المحددة.",
    
    comingSoonSashaTitle: "مستقبل ساشا: قدرات الذكاء الاصطناعي",
    comingSoonSashaDesc: "تطور ساشا لا هوادة فيه. تركز خارطة طريقنا على بناء أقوى وكيل مالي استباقي يعمل بالذكاء الاصطناعي.",
    csSashaFeature1: "رؤى استباقية وكشف الحالات الشاذة",
    csSashaFeature2: "تكامل بيانات السوق في الوقت الحقيقي (الأسهم، العملات)",
    csSashaFeature3: "لوحات معلومات مخصصة للصحة المالية",
    csSashaFeature4: "تفاعل صوتي وكلامي متقدم",
    csSashaFeature5: "خزنة وإدارة آمنة للمستندات",
    csSashaFeature6: "إنشاء وجدولة التقارير تلقائيًا",
    csSashaFeature7: "تنبؤات استشرافية للتدفقات النقدية",
    csSashaFeature8: "تكامل مع التقويم والبريد الإلكتروني للتذكيرات المالية",
    csSashaFeature9: "تحليل ومقارنة بين عدة مستندات",
    csSashaFeature10: "تخطيط المدخرات والاستثمارات القائم على الأهداف",
    csSashaFeature11: "API آمن للتكامل المؤسسي",
    csSashaFeature12: "استعلام عن قواعد البيانات باللغة الطبيعية",
    csSashaFeature13: "مراقبة التغييرات في الامتثال والتنظيمات",
    csSashaFeature14: "تحليل مشاعر العملاء من المراسلات",
    csSashaFeature15: "أتمتة سير العمل الوكيلي المخصص",

    comingSoonSpreadsheetTitle: "مستقبل جداول البيانات: القوة الوكيلية",
    comingSoonSpreadsheetDesc: "يتحول جدول البيانات إلى مساحة عمل مستقلة تمامًا، مدعومة من ساشا.",
    csSpreadsheetFeature1: "إنشاء الصيغ باللغة الطبيعية",
    csSpreadsheetFeature2: "إنشاء تلقائي للمخططات والرسوم البيانية من البيانات",
    csSpreadsheetFeature3: "قواعد التحقق من صحة البيانات مدعومة بالذكاء الاصطناعي",
    csSpreadsheetFeature4: "إنشاء فوري للجداول المحورية عبر الدردشة",
    csSpreadsheetFeature5: "تنظيف البيانات وإزالة التكرارات تلقائيًا",
    csSpreadsheetFeature6: "تنسيق شرطي ذكي",
    csSpreadsheetFeature7: "بيانات الأسهم والبيانات المالية في الوقت الحقيقي بالخلايا",
    csSpreadsheetFeature8: "استيراد تلقائي للبيانات من مصادر الويب",
    csSpreadsheetFeature9: "تحرير تعاوني مباشر بمساعدة الذكاء الاصطناعي",
    csSpreadsheetFeature10: "سجل إصدارات كامل مع ملخصات بالذكاء الاصطناعي",
    
    comingSoonDATitle: "مستقبل التحليلات: محرك ذكاء أعمال وكيلي",
    comingSoonDADesc: "نحن نعمل على تطوير ساشا لتصبح منصة ذكاء أعمال أصلية للذكاء الاصطناعي تنافس الأدوات التقليدية.",
    csDAFeature1: "إنشاء لوحة معلومات تفاعلية من الدردشة",
    csDAFeature2: "أدوات تحويل بيانات مرئية شبيهة بـ Power Query",
    csDAFeature3: "تحويل اللغة الطبيعية إلى تعبيرات شبيهة بـ DAX",
    csDAFeature4: "بناء تقارير وقصص بيانات تلقائية",
    csDAFeature5: "كشف الحالات الشاذة والتنبيهات في الوقت الحقيقي",
    csDAFeature6: "نماذج التحليلات التنبؤية والتنبؤ",
    csDAFeature7: "دمج ومزج البيانات من مصادر متعددة",
    csDAFeature8: "تحليل السبب الجذري المدعوم بالذكاء الاصطناعي",
    csDAFeature9: "مرئيات مخصصة وقابلية توسيع API",
    csDAFeature10: "إنشاء خطوط أنابيب ETL تلقائية",

    getStartedSasha: 'ابدأ مع ساشا',
    getStartedSpreadsheet: 'أو, ابدأ مع جدول البيانات',

    // Spreadsheet Page
    chatWithSasha: "الدردشة مع ساشا",
    closeChat: "إغلاق الدردشة",
    sashaSpreadsheetHello: "مرحباً! أنا مساعدة جداول بيانات وكيلية كاملة الميزات. يمكنني مساعدتك في إدخال البيانات، والنمذجة المالية، والمخططات، والمزيد. كيف يمكنني مساعدتك؟",
    spreadsheetPlaceholder: "مثال: أنشئ قالب فاتورة",
    send: "إرسال",
    showChat: "إظهار الدردشة",
    hideChat: "إخفاء الدردشة",
    importSuccessTitle: "تم الاستيراد بنجاح",
    importSuccessDesc: "تم استيراد \"{{fileName}}\" بنجاح.",
    importFailedTitle: "فشل الاستيراد",
    importFailedDesc: "حدث خطأ أثناء معالجة ملف Excel الخاص بك.",
    sashaSpreadsheetFileLoaded: "لقد قمت بتحميل \"{{fileName}}\" في جدول البيانات. كيف يمكنني مساعدتك به؟",
    sashaSpreadsheetError: "عذراً، واجهتني مشكلة. يرجى المحاولة مرة أخرى.",
    toolbarFile: "ملف",
    toolbarTemplates: "قوالب",
    templateInvoice: "فاتورة",
    templatePayroll: "كشف رواتب",
    templateExpense: "سداد المصروفات",
    templateBalanceSheet: "الميزانية العمومية",
    templateIncomeStatement: "بيان الدخل",
    templateCashFlow: "بيان التدفقات النقدية",
    templateBudget: "الميزانية الشهرية",
    templateGantt: "مخطط جانت للمشروع",
    templateGeneralLedger: "دفتر الأستاذ العام",
    templateSalesLedger: "دفتر أستاذ المبيعات",
    templatePurchaseLedger: "دفتر أستاذ المشتريات",
    templateFinancialModel: 'نموذج مالي ثلاثي القوائم',
    templateDCF: 'تقييم التدفقات النقدية المخصومة',
    templateAppliedTitle: "تم تطبيق القالب",
    templateAppliedDesc: "تم تحميل القالب في الجدول.",
    toolbarHome: "الرئيسية",
    toolbarInsert: "إدراج (قريباً)",
    toolbarFormulas: "صيغ (قريباً)",
    toolbarData: "بيانات (قريباً)",
    toolbarReview: "مراجعة (قريباً)",
    toolbarView: "عرض (قريباً)",
    toolbarFullscreen: "ملء الشاشة",
    toolbarExitFullscreen: "الخروج من ملء الشاشة",
    toolbarDownload: "تنزيل",
    toolbarImport: "استيراد",
    tooltipPaste: "لصق (استخدم Ctrl/Cmd+V)",
    tooltipCut: "قص",
    tooltipCopy: "نسخ",
    tooltipFormatPainter: "نسخ التنسيق (قريباً)",
    tooltipBold: "عريض",
    tooltipItalic: "مائل",
    tooltipUnderline: "تسطير",
    tooltipFontColor: "لون الخط",
    tooltipFillColor: "لون التعبئة",
    tooltipAlignLeft: "محاذاة لليسار",
    tooltipCenter: "توسيط",
    tooltipAlignRight: "محاذاة لليمين",
    tooltipWrapText: "التفاف النص",
    tooltipMergeCenter: "دمج وتوسيط",
    tooltipAutoSum: "جمع تلقائي (قريباً)",
    tooltipSortFilter: "فرز وتصفية (قريباً)",
    tooltipFindSelect: "بحث وتحديد (قريباً)",
    chartsTitle: "المخططات",

    // Spreadsheet Guide Page
    sgTitle: "دليل جدول البيانات",
    sgHeader: "جدول البيانات الوكيلي",
    sgSubHeader: "هذه ليست مجرد شبكة من الخلايا. إنها مساحة عمل ذكية حيث تأمر الذكاء الاصطناعي بأداء مهام معقدة. سيوضح لك هذا الدليل كيفية القيام بذلك.",
    sgCoreCapabilitiesTitle: "القدرات الأساسية",
    sgFeatureAIAssistantTitle: "مساعد الذكاء الاصطناعي",
    sgFeatureAIAssistantDesc: "استخدم اللغة الطبيعية في لوحة الدردشة لأمر ساشا بأداء أي مهمة، من إدخال البيانات إلى النمذجة المالية المعقدة.",
    sgFeatureTemplatesTitle: "قوالب قوية",
    sgFeatureTemplatesDesc: "ابدأ عملك بمكتبة من القوالب الاحترافية والمعدة مسبقًا للمحاسبة والتمويل وإدارة المشاريع.",
    sgFeatureFormulasTitle: "صيغ كاملة الميزات",
    sgFeatureFormulasDesc: "استفد من مكتبة ضخمة من مئات الوظائف، تمامًا كما في تطبيقات جداول البيانات التقليدية. يمكن لساشا بناء صيغ لك.",
    sgFeatureDataToolsTitle: "أدوات بيانات متقدمة",
    sgFeatureDataToolsDesc: "اطلب من ساشا فرز البيانات، تصفيتها، العثور على التكرارات، أو حتى إنشاء ملخصات شبيهة بالجداول المحورية على الفور.",
    sgGettingStartedTitle: "كيف يعمل: سير عملك في 3 خطوات",
    sgGettingStartedDesc: "العمل مع جدول البيانات الوكيلي هو عملية محادثة بسيطة.",
    sgStep1Title: "ابدأ بالبيانات",
    sgStep1Desc: "يمكنك البدء بصفحة فارغة، أو استيراد ملف Excel/CSV موجود، أو تحديد قالب مُعد مسبقًا من قائمة 'القوالب'.",
    sgStep2Title: "أصدر أمرًا لساشا",
    sgStep2Desc: "استخدم لوحة الدردشة على اليمين لإخبار ساشا بما تريد القيام به باللغة الإنجليزية أو العربية البسيطة.",
    sgStep2Example: "احسب صافي الربح للربع الثالث وقم بتمييزه باللون الأخضر.",
    sgStep3Title: "راجع النتيجة",
    sgStep3Desc: "ستقوم ساشا بتفسير أمرك، وإجراء العمليات اللازمة (مثل إدراج الصيغ وتطبيق التنسيق)، وتأكيد الإجراء. يتم تحديث الجدول على الفور.",
    sgStep3Example: "تم. لقد حسبت صافي الربح في الخلية E14 وطبقت التنسيق.",
    sgSashaCommandsTitle: "أوامر مثال لساشا",
    sgCmdDataEntryTitle: "إدخال البيانات ومسك الدفاتر",
    sgCmdDataEntryDesc: "يمكن أن تعمل ساشا كمحاسب آلي لك.",
    sgCmdDataEntryExample: "سجل عملية بيع 500 وحدة بسعر 12.50 دولارًا لكل منها إلى 'شركة المثال' بتاريخ اليوم.",
    sgCmdFinancialAnalysisTitle: "التحليل المالي والنمذجة",
    sgCmdFinancialAnalysisDesc: "اطلب من ساشا إجراء حسابات مالية معقدة.",
    sgCmdFinancialAnalysisExample: "ما هي صافي القيمة الحالية للتدفقات النقدية في C5:C10 بمعدل خصم 8%؟",
    sgCmdFormattingTitle: "التنسيق والتدقيق",
    sgCmdFormattingDesc: "أتمتة التنظيم البصري والتحقق من صحة البيانات.",
    sgCmdFormattingExample: "ابحث عن جميع الصفوف حيث يكون العمود D أكبر من العمود C واجعل خلفيتها حمراء فاتحة.",
    sgCmdChartsTitle: "المخططات والتصور",
    sgCmdChartsDesc: "حوّل بياناتك إلى رؤى.",
    sgCmdChartsExample: "أنشئ مخططًا شريطيًا يوضح إجمالي المبيعات حسب المنطقة من العمودين A و F.",
    sgFunctionLibraryTitle: "مكتبة الوظائف والصيغ",
    sgFunctionLibraryDesc: "ساشا بارعة في مكتبة واسعة من الوظائف ويمكنها إنشاء صيغ عند الطلب. إليك بعض الوظائف الرئيسية المتاحة:",
    sgFuncMathLogicTitle: "الرياضيات والمنطق",
    sgFuncLookupTitle: "البحث والمراجع",
    sgFuncFinancialTitle: "المالية",
    sgFuncTextTitle: "النص",
    sgFuncDateTimeTitle: "التاريخ والوقت",
    sgFuncStatisticalTitle: "الإحصاء والتنبؤ",

    // Data Analytics Page
    daUploadPromptTitle: "لوحة معلومات مدعومة بالذكاء الاصطناعي",
    daUploadPromptDesc: "قم بتحميل ملف البيانات الخاص بك (XLSX، CSV، أو PDF) لتقوم ساشا بتحليله وإنشاء لوحة معلومات تفاعلية.",
    daUploadButton: "تحميل ملف البيانات",
    daGeneratingDashboardTitle: "جاري إنشاء لوحة معلومات الذكاء الاصطناعي...",
    daGeneratingDashboardDesc: "يرجى الانتظار بينما تقوم ساشا بتحليل بياناتك وبناء لوحة معلوماتك.",
    analysisResultTitle: "نتيجة التحليل",
    daSummaryTitle: "ملخص الذكاء الاصطناعي",
    daUnsupportedFileType: 'نوع ملف غير مدعوم. يرجى تحميل ملف CSV أو XLSX أو PDF.',
    daAnalysisFailedDesc: 'فشل التحليل. قد يكون الملف تالفًا أو بتنسيق غير مدعوم أو أن نموذج الذكاء الاصطناعي غير متاح حاليًا.',
    daKeyInsightsTitle: 'رؤى رئيسية',
    daDownloadPdfButton: 'تحميل PDF',
    daGeneratingPdfTitle: 'جاري إنشاء تقرير PDF...',
    daPdfGenerationFailedTitle: 'فشل إنشاء PDF',
    daPdfGenerationFailedDesc: 'حدث خطأ أثناء محاولة إنشاء تقرير PDF.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  const t = (key: string, replacements?: { [key: string]: string | number }) => {
    let translation = translations[language][key] || key;
    if (replacements) {
        Object.keys(replacements).forEach(rKey => {
            translation = translation.replace(`{{${rKey}}}`, String(replacements[rKey]));
        });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
