'use client';

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: { [key: string]: string | number }) => string;
  dir: 'ltr' | 'rtl';
}

const translations: { [key in Language]: { [key: string]: string } } = {
  en: {
    pageTitle: 'Sasha Banking',
    initialMessage: "Hello! I'm Sasha, your financial advisor. How can I help you today?",
    placeholder: "Message Sasha...",
    uploadCsvTooltip: "Upload Loan CSV",
    uploadPdfTooltip: "Upload Financial PDF",
    micTooltip: "Use Microphone",
    sendSr: "Send",
    analyzingFile: "Context: {{fileName}}",
    clearPdfTooltip: "Clear PDF from session",
    pdfClearedTitle: "PDF Cleared",
    pdfClearedDesc: "The document has been removed from the session.",
    clearedPdfMessage: "I have cleared the previous document. How can I assist you now?",
    csvUploadTitle: "CSV File Uploaded",
    csvUploadDesc: "{{fileName}} is ready for loan analysis.",
    pdfUploadTitle: "PDF File Uploaded",
    pdfUploadDesc: "{{fileName}} is ready for chat.",
    pdfLoadedForChat: "I've loaded {{fileName}}. Feel free to ask me any questions about it.",
    analyzingPdfMessage: "Analyzing the financial statement: {{fileName}}...",
    analysisFailedTitle: "Analysis Failed",
    analysisFailedDesc: "Sasha could not analyze the financial statement. Please try again.",
    unableToAnalyzeMessage: 'Sorry, I was unable to analyze that document.',
    loanAnalysisHeader: "Here is the analysis for Loan ID **{{loanId}}**:",
    financialAnalysisHeader: "Here is the analysis of the financial statement:",
    uploadCsvFirst: 'Please upload a CSV file first.',
    invalidPdfTitle: 'Invalid File Type',
    invalidPdfDesc: 'Please upload a PDF file.',
    sessionSaveErrorTitle: 'Could not save session',
    sessionSaveErrorDesc: 'Your browser may be out of space or in private mode.',
    documentLoadedTitle: 'Document Loaded',
    documentLoadedDesc: "Continuing session with {{fileName}}.",
    genericErrorTitle: 'Oh no! Something went wrong.',
    genericErrorDesc: 'Failed to get a response from Sasha. Please try again.',
    loanAnalysisReportTitle: "Loan Analysis Report",
    financialAnalysisReportTitle: "Financial Statement Analysis",
    summary: "Summary",
    prediction: "Prediction",
    eligibility: "Eligibility",
    creditScoreAssessment: "Credit Score Assessment",
    downloadPdf: "Download PDF",
    english: 'English',
    arabic: 'Arabic',
    choosePdfLanguageTitle: "Choose PDF Language",
    choosePdfLanguageDesc: "In which language would you like to download the report?",
    cancel: "Cancel",
    clearCsvTooltip: "Clear CSV from session",
    csvClearedTitle: "CSV Cleared",
    csvClearedDesc: "The CSV data has been cleared from the session.",
    clearedCsvMessage: "I have cleared the CSV data. How can I help you now?",
    translationErrorTitle: 'Translation Error',
    translationErrorDesc: 'Failed to generate the report in {{lang}}. Please try again.',
    generatingTranslatedPdf: 'Generating translated PDF...',
    trendsAndGraphsTitle: "Trends & Visualizations",
    identifiedFlawsTitle: "Identified Flaws & Risks",
    financialPerformanceTitle: "Financial Performance",
    revenue: "Revenue",
    netIncome: "Net Income",
    pdfGenerationError: "Could not generate the PDF report.",
    maintenanceMessage: "Services are undergoing maintenance and major upgrades. Time remaining: {{time}}",
    imageDialogTitle: "AI Image Generation",
    imageDialogDesc: "Describe the image you want Sasha to create. Be as descriptive as you like.",
    promptLabel: "Prompt",
    promptPlaceholder: "e.g., A futuristic city skyline at sunset",
    generateButton: "Generate",
    generatingMessage: "Sasha is creating your image...",
    generateAnotherButton: "Generate Another",
    downloadButton: "Download",
    addToChatButton: "Add to Chat",
    imageGenSuccess: "Here is the image I created based on your prompt: \"{{prompt}}\"",
    imageGenFailedTitle: "Image Generation Failed",
    imageGenFailedDesc: "Sorry, I couldn't create an image at this time. Please try again later.",
    imageGenDisclaimer: "Sasha's creative abilities are powered by a specialized image generation model. Generated images are for creative use.",

    // Nav
    chatTitle: 'Chat',
    learnTitle: 'About',
    spreadsheetTitle: 'Spreadsheet',

    // Learn Page
    learnPageTitle: 'About Sasha',
    learnIntro: 'Sasha is an advanced, AI-powered financial strategist and banking assistant designed to bring institutional-grade analysis and agentic task execution to your fingertips. Interact naturally, get deep insights, and automate complex tasks with ease.',
    learnCapabilitiesTitle: "Sasha's Core Capabilities",
    learnChatTitle: 'Institutional-Grade Financial Intelligence',
    learnChatDesc: "Engage with an AI that understands the nuances of finance. Upload complex financial statements, credit reports from bureaus like Oman's Mala'a, or internal loan data. Sasha doesn't just read; she comprehends, synthesizes, and critiques. Ask her to 'Identify key risks in this balance sheet,' 'Benchmark this company's P/E ratio against industry standards,' or 'Draft a summary for the credit committee.' Sasha provides instant, institutional-quality analysis in both English and Arabic, becoming an indispensable partner for credit officers, analysts, and decision-makers.",
    learnSpreadsheetTitle: 'The Truly Agentic Spreadsheet',
    learnSpreadsheetDesc: "This is not just a spreadsheet; it's an intelligent workspace. Command Sasha with natural language to perform tasks that once took hours. Say 'Create a 5-year financial forecast based on this historical data,' 'Generate a Gantt chart for the Q4 product launch,' or 'Analyze these sales figures and highlight all regions that underperformed by 15%.' Sasha functions as a state-of-the-art AI architect, understanding your intent, structuring the data, applying formats, and executing complex operations instantly, transforming your productivity.",
    learnAITitle: 'Powered by a State-of-the-Art AI Architecture',
    learnAIDesc: "Sasha is built on a private, state-of-the-art AI architecture. This enables her to understand complex documents, reason about data, follow multi-step instructions, and generate human-like text, making her a powerful and versatile financial partner.",
    learnSecurityTitle: 'Enterprise-Grade Security & Privacy',
    learnSecurityDesc: "Sasha is engineered with security as a foundational principle. Operating within a private, state-of-the-art architecture, all data processing and interactions are handled with the strictest confidentiality. Your financial statements, proprietary data, and sensitive conversations are never used for external training models. With end-to-end encryption and robust access controls, Sasha provides a secure, compliant environment that meets the rigorous standards of financial institutions, ensuring your most critical information remains protected.",
    learnWhoBenefitsTitle: 'Who Benefits from Sasha?',
    learnRoleAnalystTitle: 'The Financial Analyst',
    learnRoleAnalystDesc: 'Accelerate your research, data modeling, and report generation. Let Sasha handle the repetitive tasks so you can focus on strategic insights.',
    learnRoleOfficerTitle: 'The Credit Officer',
    learnRoleOfficerDesc: 'Gain a deeper, faster understanding of applicant risk. Analyze financial statements and credit reports in seconds to make more informed decisions.',
    learnRoleExecutiveTitle: 'The Executive',
    learnRoleExecutiveDesc: 'Access high-level summaries and key metrics on demand. Stay informed and drive strategy without getting bogged down in the details.',
    gettingStartedTitle: "Getting Started: A Quick Guide",
    gsChatStepTitle: "1. Start a Conversation",
    gsChatStepDesc: "Navigate to the <strong>Chat</strong> page. You can start talking to Sasha immediately. For more powerful analysis, use the upload buttons in the message bar to provide a PDF or CSV file as context for your conversation.",
    gsSpreadsheetStepTitle: "2. Command Your Spreadsheet",
    gsSpreadsheetStepDesc: "Go to the <strong>Spreadsheet</strong> page. Use the integrated chat sidebar to give Sasha commands. You can also import your own Excel files using the toolbar to have Sasha work with your own data.",
    
    comingSoonSashaTitle: "The Future of Sasha: AI Capabilities",
    comingSoonSashaDesc: "Sasha's evolution is relentless. Our roadmap is focused on building the most powerful, proactive AI financial agent.",
    csSashaFeature1: "Proactive Insights & Anomaly Detection",
    csSashaFeature2: "Real-time Market Data Integration (stocks, forex)",
    csSashaFeature3: "Personalized Financial Health Dashboards",
    csSashaFeature4: "Advanced Voice & Speech Interaction",
    csSashaFeature5: "Secure Document Vault & Management",
    csSashaFeature6: "Automated Report Generation & Scheduling",
    csSashaFeature7: "Predictive Cash Flow Forecasting",
    csSashaFeature8: "Calendar & Email Integration for Financial Reminders",
    csSashaFeature9: "Multi-document Cross-Referencing & Analysis",
    csSashaFeature10: "Goal-based Savings & Investment Planning",
    csSashaFeature11: "Secure API for Enterprise Integration",
    csSashaFeature12: "Natural Language Querying of Databases",
    csSashaFeature13: "Compliance & Regulatory Change Monitoring",
    csSashaFeature14: "Customer Sentiment Analysis from Communications",
    csSashaFeature15: "Custom Agentic Workflow Automation",

    comingSoonSpreadsheetTitle: "The Future of Spreadsheets: Agentic Power",
    comingSoonSpreadsheetDesc: "The spreadsheet is becoming a fully autonomous workspace, powered by Sasha.",
    csSpreadsheetFeature1: "Natural Language Formula Generation",
    csSpreadsheetFeature2: "Automatic Chart & Graph Creation from Data",
    csSpreadsheetFeature3: "AI-Powered Data Validation Rules",
    csSpreadsheetFeature4: "Instant Pivot Table Creation via Chat",
    csSpreadsheetFeature5: "Automated Data Cleaning & Deduplication",
    csSpreadsheetFeature6: "Intelligent Conditional Formatting",
    csSpreadsheetFeature7: "Real-time Stock & Financial Data in Cells",
    csSpreadsheetFeature8: "Automated Data Import from Web Sources",
    csSpreadsheetFeature9: "Live Collaborative Editing with AI Assistance",
    csSpreadsheetFeature10: "Full Version History with AI Summaries",
    getStartedSasha: 'GET STARTED WITH SASHA',
    getStartedSpreadsheet: 'Or, get started with the Spreadsheet',

    // Spreadsheet Page
    chatWithSasha: "Chat with Sasha",
    closeChat: "Close chat",
    sashaSpreadsheetHello: "Hello! I'm Sasha. I can help you create, format, and analyze this spreadsheet. Just tell me what you need.",
    spreadsheetPlaceholder: "e.g., Make row 1 bold and blue",
    send: "Send",
    showChat: "Show Chat",
    hideChat: "Hide Chat",
    importSuccessTitle: "Import Successful",
    importSuccessDesc: "Successfully imported \"{{fileName}}\".",
    importFailedTitle: "Import Failed",
    importFailedDesc: "There was an error processing your Excel file.",
    sashaSpreadsheetFileLoaded: "I've loaded \"{{fileName}}\" into the spreadsheet. How can I help you with it?",
    sashaSpreadsheetError: "Sorry, I ran into an issue. Please try that again.",
    toolbarFile: "File",
    toolbarHome: "Home",
    toolbarInsert: "Insert (Coming Soon)",
    toolbarFormulas: "Formulas (Coming Soon)",
    toolbarData: "Data (Coming Soon)",
    toolbarReview: "Review (Coming Soon)",
    toolbarView: "View (Coming Soon)",
    toolbarFullscreen: "Fullscreen",
    toolbarExitFullscreen: "Exit Fullscreen",
    toolbarDownload: "Download",
    toolbarImport: "Import",
    tooltipPaste: "Paste (Use Ctrl/Cmd+V)",
    tooltipCut: "Cut",
    tooltipCopy: "Copy",
    tooltipFormatPainter: "Format Painter (Coming Soon)",
    tooltipBold: "Bold",
    tooltipItalic: "Italic",
    tooltipUnderline: "Underline",
    tooltipFontColor: "Font Color (Coming Soon)",
    tooltipAlignLeft: "Align Left",
    tooltipCenter: "Center",
    tooltipAlignRight: "Align Right",
    tooltipWrapText: "Wrap Text",
    tooltipMergeCenter: "Merge & Center",
    tooltipAutoSum: "AutoSum (Coming Soon)",
    tooltipSortFilter: "Sort & Filter (Coming Soon)",
    tooltipFindSelect: "Find & Select (Coming Soon)",
  },
  ar: {
    pageTitle: 'ساشا المصرفية',
    initialMessage: "مرحباً! أنا ساشا، مستشاركتك المالية. كيف يمكنني مساعدتك اليوم؟",
    placeholder: "راسل ساشا...",
    uploadCsvTooltip: "تحميل ملف CSV للقروض",
    uploadPdfTooltip: "تحميل ملف PDF مالي",
    micTooltip: "استخدام الميكروفون",
    sendSr: "إرسال",
    analyzingFile: "السياق: {{fileName}}",
    clearPdfTooltip: "مسح ملف PDF من الجلسة",
    pdfClearedTitle: "تم مسح PDF",
    pdfClearedDesc: "تمت إزالة المستند من الجلسة.",
    clearedPdfMessage: "لقد قمت بمسح المستند السابق. كيف يمكنني مساعدتك الآن؟",
    csvUploadTitle: "تم تحميل ملف CSV",
    csvUploadDesc: "{{fileName}} جاهز لتحليل القرض.",
    pdfUploadTitle: "تم تحميل ملف PDF",
    pdfUploadDesc: "{{fileName}} جاهز للمحادثة.",
    pdfLoadedForChat: "لقد قمت بتحميل {{fileName}}. لا تتردد في طرح أي أسئلة حوله.",
    analyzingPdfMessage: "جاري تحليل البيان المالي: {{fileName}}...",
    analysisFailedTitle: "فشل التحليل",
    analysisFailedDesc: "لم تتمكن ساشا من تحليل البيان المالي. يرجى المحاولة مرة أخرى.",
    unableToAnalyzeMessage: 'عذراً، لم أتمكن من تحليل ذلك المستند.',
    loanAnalysisHeader: "إليك تحليل معرف القرض **{{loanId}}**:",
    financialAnalysisHeader: "إليك تحليل البيان المالي:",
    uploadCsvFirst: 'يرجى تحميل ملف CSV أولاً.',
    invalidPdfTitle: 'نوع ملف غير صالح',
    invalidPdfDesc: 'يرجى تحميل ملف PDF.',
    sessionSaveErrorTitle: 'تعذر حفظ الجلسة',
    sessionSaveErrorDesc: 'قد تكون مساحة متصفحك ممتلئة أو في وضع التصفح الخاص.',
    documentLoadedTitle: 'تم تحميل المستند',
    documentLoadedDesc: "متابعة الجلسة مع {{fileName}}.",
    genericErrorTitle: 'عفوًا! حدث خطأ ما.',
    genericErrorDesc: 'فشل الحصول على رد من ساشا. يرجى المحاولة مرة أخرى.',
    loanAnalysisReportTitle: "تقرير تحليل القرض",
    financialAnalysisReportTitle: "تحليل البيان المالي",
    summary: "ملخص",
    prediction: "توقع",
    eligibility: "الأهلية",
    creditScoreAssessment: "تقييم الجدارة الائتمانية",
    downloadPdf: "تحميل PDF",
    english: 'الإنجليزية',
    arabic: 'العربية',
    choosePdfLanguageTitle: "اختر لغة التقرير",
    choosePdfLanguageDesc: "بأي لغة تود تحميل التقرير؟",
    cancel: "إلغاء",
    clearCsvTooltip: "مسح ملف CSV من الجلسة",
    csvClearedTitle: "تم مسح CSV",
    csvClearedDesc: "تمت إزالة بيانات CSV من الجلسة.",
    clearedCsvMessage: "لقد قمت بمسح بيانات CSV. كيف يمكنني مساعدتك الآن؟",
    translationErrorTitle: 'خطأ في الترجمة',
    translationErrorDesc: 'فشل إنشاء التقرير باللغة {{lang}}. يرجى المحاولة مرة أخرى.',
    generatingTranslatedPdf: 'جاري إنشاء ملف PDF مترجم...',
    trendsAndGraphsTitle: "الاتجاهات والتصورات",
    identifiedFlawsTitle: "العيوب والمخاطر المحددة",
    financialPerformanceTitle: "الأداء المالي",
    revenue: "الإيرادات",
    netIncome: "صافي الدخل",
    pdfGenerationError: "تعذر إنشاء تقرير PDF.",
    maintenanceMessage: "تخضع الخدمات للصيانة والتحديثات الرئيسية. الوقت المتبقي: {{time}}",
    imageDialogTitle: "إنشاء صورة بالذكاء الاصطناعي",
    imageDialogDesc: "صف الصورة التي تريد أن تنشئها ساشا. كن وصفيًا كما تريد.",
    promptLabel: "الموجه",
    promptPlaceholder: "مثال: أفق مدينة مستقبلية عند غروب الشمس",
    generateButton: "إنشاء",
    generatingMessage: "ساشا تنشئ صورتك...",
    generateAnotherButton: "إنشاء واحدة أخرى",
    downloadButton: "تنزيل",
    addToChatButton: "إضافة إلى الدردشة",
    imageGenSuccess: "هذه هي الصورة التي أنشأتها بناءً على موجهك: \"{{prompt}}\"",
    imageGenFailedTitle: "فشل إنشاء الصورة",
    imageGenFailedDesc: "عذرًا، لم أتمكن من إنشاء صورة في هذا الوقت. يرجى المحاولة مرة أخرى لاحقًا.",
    imageGenDisclaimer: "قدرات ساشا الإبداعية مدعومة بنموذج متخصص لتوليد الصور. الصور المنشأة للاستخدام الإبداعي.",

    // Nav
    chatTitle: 'الدردشة',
    learnTitle: 'حول ساشا',
    spreadsheetTitle: 'جدول البيانات',

    // Learn Page
    learnPageTitle: 'حول ساشا',
    learnIntro: 'ساشا هي خبيرة استراتيجية مالية ومساعدة مصرفية متقدمة تعمل بالذكاء الاصطناعي، مصممة لتوفر لك تحليلات على مستوى المؤسسات وتنفيذ مهام وكيلية بكل سهولة. تفاعل بشكل طبيعي، واحصل على رؤى عميقة، وقم بأتمتة المهام المعقدة.',
    learnCapabilitiesTitle: "قدرات ساشا الأساسية",
    learnChatTitle: 'ذكاء مالي من الطراز المؤسسي',
    learnChatDesc: "تفاعل مع ذكاء اصطناعي يفهم دقائق الأمور المالية. قم بتحميل بيانات مالية معقدة، تقارير ائتمانية من مكاتب مثل 'ملاءة' في عُمان، أو بيانات قروض داخلية. ساشا لا تقرأ فقط؛ بل تفهم، وتحلل، وتنتقد. اطلب منها 'تحديد المخاطر الرئيسية في هذه الميزانية العمومية'، 'مقارنة نسبة السعر إلى الأرباح لهذه الشركة بمعايير الصناعة'، أو 'صياغة ملخص للجنة الائتمان'. تقدم ساشا تحليلاً فوريًا بجودة مؤسسية باللغتين الإنجليزية والعربية، لتصبح شريكًا لا غنى عنه لمسؤولي الائتمان والمحللين وصناع القرار.",
    learnSpreadsheetTitle: 'جدول البيانات الوكيلي الحقيقي',
    learnSpreadsheetDesc: "هذا ليس مجرد جدول بيانات؛ إنها مساحة عمل ذكية. أصدر أوامر لساشا بلغة طبيعية لأداء مهام كانت تستغرق ساعات. قل 'أنشئ توقعات مالية لمدة 5 سنوات بناءً على هذه البيانات التاريخية'، 'أنشئ مخطط جانت لإطلاق منتج الربع الرابع'، أو 'حلل أرقام المبيعات هذه وقم بتمييز جميع المناطق التي كان أداؤها أقل بنسبة 15%'. تعمل ساشا كمهندس معماري للذكاء الاصطناعي على أحدث طراز، حيث تفهم نيتك، وتنظم البيانات، وتطبق التنسيقات، وتنفذ العمليات المعقدة على الفور، مما يغير إنتاجيتك.",
    learnAITitle: 'مدعومة ببنية تحتية حديثة للذكاء الاصطناعي',
    learnAIDesc: "ساشا مبنية على بنية تحتية خاصة وحديثة للذكاء الاصطناعي. وهذا يمكنها من فهم المستندات المعقدة، والاستدلال على البيانات، واتباع التعليمات متعددة الخطوات، وإنشاء نصوص شبيهة بالإنسان، مما يجعلها شريكًا ماليًا قويًا ومتعدد الاستخدامات.",
    learnSecurityTitle: 'أمان وخصوصية على مستوى المؤسسات',
    learnSecurityDesc: "تم تصميم ساشا مع اعتبار الأمان مبدأً أساسيًا. تعمل ضمن بنية خاصة وحديثة، حيث يتم التعامل مع جميع عمليات معالجة البيانات والتفاعلات بأقصى درجات السرية. لا يتم استخدام بياناتك المالية، وبيانات الملكية، والمحادثات الحساسة أبدًا لتدريب النماذج الخارجية. مع التشفير من طرف إلى طرف وضوابط الوصول القوية، توفر ساشا بيئة آمنة ومتوافقة تلبي المعايير الصارمة للمؤسسات المالية، مما يضمن حماية معلوماتك الأكثر أهمية.",
    learnWhoBenefitsTitle: 'من يستفيد من ساشا؟',
    learnRoleAnalystTitle: 'المحلل المالي',
    learnRoleAnalystDesc: 'سرّع أبحاثك، ونمذجة البيانات، وإعداد التقارير. دع ساشا تتولى المهام المتكررة حتى تتمكن من التركيز على الرؤى الاستراتيجية.',
    learnRoleOfficerTitle: 'مسؤول الائتمان',
    learnRoleOfficerDesc: 'احصل على فهم أعمق وأسرع لمخاطر المتقدمين. حلل البيانات المالية وتقارير الائتمان في ثوانٍ لاتخاذ قرارات أكثر استنارة.',
    learnRoleExecutiveTitle: 'المدير التنفيذي',
    learnRoleExecutiveDesc: 'احصل على ملخصات عالية المستوى ومقاييس رئيسية عند الطلب. ابق على اطلاع وادفع بالاستراتيجية دون الغرق في التفاصيل.',
    gettingStartedTitle: "البدء: دليل سريع",
    gsChatStepTitle: "١. ابدأ محادثة",
    gsChatStepDesc: "انتقل إلى صفحة <strong>الدردشة</strong>. يمكنك البدء في التحدث إلى ساشا على الفور. لتحليل أقوى، استخدم أزرار التحميل في شريط الرسائل لتوفير ملف PDF أو CSV كسياق لمحادثتك.",
    gsSpreadsheetStepTitle: "٢. تحكم في جدول بياناتك",
    gsSpreadsheetStepDesc: "اذهب إلى صفحة <strong>جدول البيانات</strong>. استخدم الشريط الجانبي للدردشة المدمج لإعطاء أوامر لساشا. يمكنك أيضًا استيراد ملفات Excel الخاصة بك باستخدام شريط الأدوات لجعل ساشا تعمل مع بياناتك الخاصة.",
    
    comingSoonSashaTitle: "مستقبل ساشا: قدرات الذكاء الاصطناعي",
    comingSoonSashaDesc: "تطور ساشا لا هوادة فيه. تركز خارطة طريقنا على بناء أقوى وكيل مالي استباقي يعمل بالذكاء الاصطناعي.",
    csSashaFeature1: "رؤى استباقية وكشف الحالات الشاذة",
    csSashaFeature2: "تكامل بيانات السوق في الوقت الحقيقي (الأسهم، العملات)",
    csSashaFeature3: "لوحات معلومات مخصصة للصحة المالية",
    csSashaFeature4: "تفاعل صوتي وكلامي متقدم",
    csSashaFeature5: "خزنة وإدارة آمنة للمستندات",
    csSashaFeature6: "إنشاء وجدولة التقارير تلقائيًا",
    csSashaFeature7: "تنبؤات استشرافية للتدفقات النقدية",
    csSashaFeature8: "تكامل مع التقويم والبريد الإلكتروني للتذكيرات المالية",
    csSashaFeature9: "تحليل ومقارنة بين عدة مستندات",
    csSashaFeature10: "تخطيط المدخرات والاستثمارات القائم على الأهداف",
    csSashaFeature11: "API آمن للتكامل المؤسسي",
    csSashaFeature12: "استعلام عن قواعد البيانات باللغة الطبيعية",
    csSashaFeature13: "مراقبة التغييرات في الامتثال والتنظيمات",
    csSashaFeature14: "تحليل مشاعر العملاء من المراسلات",
    csSashaFeature15: "أتمتة سير العمل الوكيلي المخصص",

    comingSoonSpreadsheetTitle: "مستقبل جداول البيانات: القوة الوكيلية",
    comingSoonSpreadsheetDesc: "يتحول جدول البيانات إلى مساحة عمل مستقلة تمامًا، مدعومة من ساشا.",
    csSpreadsheetFeature1: "إنشاء الصيغ باللغة الطبيعية",
    csSpreadsheetFeature2: "إنشاء تلقائي للمخططات والرسوم البيانية من البيانات",
    csSpreadsheetFeature3: "قواعد التحقق من صحة البيانات مدعومة بالذكاء الاصطناعي",
    csSpreadsheetFeature4: "إنشاء فوري للجداول المحورية عبر الدردشة",
    csSpreadsheetFeature5: "تنظيف البيانات وإزالة التكرارات تلقائيًا",
    csSpreadsheetFeature6: "تنسيق شرطي ذكي",
    csSpreadsheetFeature7: "بيانات الأسهم والبيانات المالية في الوقت الحقيقي بالخلايا",
    csSpreadsheetFeature8: "استيراد تلقائي للبيانات من مصادر الويب",
    csSpreadsheetFeature9: "تحرير تعاوني مباشر بمساعدة الذكاء الاصطناعي",
    csSpreadsheetFeature10: "سجل إصدارات كامل مع ملخصات بالذكاء الاصطناعي",
    getStartedSasha: 'ابدأ مع ساشا',
    getStartedSpreadsheet: 'أو, ابدأ مع جدول البيانات',

    // Spreadsheet Page
    chatWithSasha: "الدردشة مع ساشا",
    closeChat: "إغلاق الدردشة",
    sashaSpreadsheetHello: "مرحباً! أنا ساشا. يمكنني مساعدتك في إنشاء وتنسيق وتحليل جدول البيانات هذا. فقط أخبرني بما تحتاجه.",
    spreadsheetPlaceholder: "مثال: اجعل الصف الأول عريضًا وأزرق",
    send: "إرسال",
    showChat: "إظهار الدردشة",
    hideChat: "إخفاء الدردشة",
    importSuccessTitle: "تم الاستيراد بنجاح",
    importSuccessDesc: "تم استيراد \"{{fileName}}\" بنجاح.",
    importFailedTitle: "فشل الاستيراد",
    importFailedDesc: "حدث خطأ أثناء معالجة ملف Excel الخاص بك.",
    sashaSpreadsheetFileLoaded: "لقد قمت بتحميل \"{{fileName}}\" في جدول البيانات. كيف يمكنني مساعدتك به؟",
    sashaSpreadsheetError: "عذراً، واجهتني مشكلة. يرجى المحاولة مرة أخرى.",
    toolbarFile: "ملف",
    toolbarHome: "الرئيسية",
    toolbarInsert: "إدراج (قريباً)",
    toolbarFormulas: "صيغ (قريباً)",
    toolbarData: "بيانات (قريباً)",
    toolbarReview: "مراجعة (قريباً)",
    toolbarView: "عرض (قريباً)",
    toolbarFullscreen: "ملء الشاشة",
    toolbarExitFullscreen: "الخروج من ملء الشاشة",
    toolbarDownload: "تنزيل",
    toolbarImport: "استيراد",
    tooltipPaste: "لصق (استخدم Ctrl/Cmd+V)",
    tooltipCut: "قص",
    tooltipCopy: "نسخ",
    tooltipFormatPainter: "نسخ التنسيق (قريباً)",
    tooltipBold: "عريض",
    tooltipItalic: "مائل",
    tooltipUnderline: "تسطير",
    tooltipFontColor: "لون الخط (قريباً)",
    tooltipAlignLeft: "محاذاة لليسار",
    tooltipCenter: "توسيط",
    tooltipAlignRight: "محاذاة لليمين",
    tooltipWrapText: "التفاف النص",
    tooltipMergeCenter: "دمج وتوسيط",
    tooltipAutoSum: "جمع تلقائي (قريباً)",
    tooltipSortFilter: "فرز وتصفية (قريباً)",
    tooltipFindSelect: "بحث وتحديد (قريباً)",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  const t = (key: string, replacements?: { [key: string]: string | number }) => {
    let translation = translations[language][key] || key;
    if (replacements) {
        Object.keys(replacements).forEach(rKey => {
            translation = translation.replace(`{{${rKey}}}`, String(replacements[rKey]));
        });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
